[profile.default]
src = "src"
test = "test"
script = "script"
out = "out"
libs = ["lib"]
solc = "0.8.28"
optimizer = true
optimizer_runs = 200
evm_version = "cancun"
remappings = [
    "@openzeppelin/contracts/=lib/openzeppelin-contracts/contracts/",
    "forge-std/=lib/forge-std/src/",
]

[fmt]
line_length = 120
tab_width = 4
bracket_spacing = false
int_types = "long"

# Reti L2 — Base (gli URL arrivano da .env / variabili d'ambiente)
[rpc_endpoints]
base_sepolia = "${BASE_SEPOLIA_RPC_URL}"
base = "${BASE_MAINNET_RPC_URL}"
